### ISSUE TITLE
Line comments

### ISSUE THREAD

**Issue by everdimension** [atom/language-less#31]
`Cmd + /` activates only css block-comments.

How to activate line comments? Because `less` supports them, so this language-package should, too.

**Comment by mnquintana** [comment]
That's strange – <kbd>Cmd-/</kbd> should toggle line comments in Less. Does this happen in safe mode too? (`atom --safe`)

**Comment by everdimension** [comment]
Hm, no, it works as it should in safe mode. But looks like other plugins are disabled in --safe, `vim-mode`, for example. May be it is the one conflicting, may be not.

**Comment by mnquintana** [comment]
Can you post a list of your installed packages? (`apm list --installed`)

**Comment by everdimension** [comment]
Sure.
```sh
├── atom-alignment@0.12.1
├── emmet@2.3.9
├── file-icons@1.5.5
├── highlight-selected@0.9.3
├── react@0.11.8
├── seti-ui@0.7.1
└── vim-mode@0.48.0
```

**Comment by mnquintana** [comment]
Can you try disabling emmet and see if that fixes it?

**Comment by everdimension** [comment]
It did, thanks. Sorry for the disturbance...guess I'd better go disturb emmet folks :)

**Comment by mnquintana** [comment]
No worries! Glad you found it :+1:
