### ISSUE TITLE
Parent selectors highlighted incorrectly

### ISSUE THREAD

**Issue by mistadikay** [atom/language-less#32]
When using parent selector + underscores as a part of a child selector, highlighting doesn't work correctly.

![screen shot 2015-05-24 at 14 31 22](https://cloud.githubusercontent.com/assets/742056/7787084/bd747df0-0221-11e5-9e8f-30ca969968ec.png)

When there are hyphens instead of underscores, everything is better, but still not quite right.
![screen shot 2015-05-24 at 14 46 31](https://cloud.githubusercontent.com/assets/742056/7787112/b5a3388a-0223-11e5-8994-12c625927469.png)

Expected behavior: it should be highlighted as css class in this case

Atom v0.201.0 @ OSX 10.10.3

**Comment by burodepeper** [comment]
I assume you want to use `__logo-link` as a css class. If that's the case, then there's just an error in your markup and not in the highlighting. Try the following (note the . to designate the class):
```less
.header {
  font-size: 18px;
  &.__logo-link {
    margin-right: 20px;
  }
}
```

**Comment by mistadikay** [comment]
@burodepeper well not really. I want to use `.header` as a part of another class, so I'd have `.header__logo-link` in the end. It's [BEM](https://en.bem.info) naming convention meaning that `logo-link` is an _element_ of `header` _block_. Also please take a look at [less docs](http://lesscss.org/features/#parent-selectors-feature) part about parent selectors.

Anyway, it looks like this bug has been fixed since I reported it, so I guess I can just close this issue. See screenshot below confirming correct behaviour with `language-less@0.28.2`:
<img width="236" alt="screen shot 2015-08-24 at 09 51 58" src="https://cloud.githubusercontent.com/assets/742056/9432017/e16a5ae2-4a45-11e5-87d5-37907be54dd3.png">
