### ISSUE TITLE
Incorrect highlighting of hex colors on lines with variable interpolation

### ISSUE THREAD

**Issue by ToadKing** [atom/language-less#37]
```less
a {
  background: #0F0F0F url("@{variable}/test.png");
}
```

This has incorrect highlighting on the hex color in Atom. The decimal numbers are correctly colored, but the hash and F digits are not. Taking out the `@{variable}` line fixes it.

Tested in Atom 1.0.2 on Windows.

**Comment by braver** [comment]
Fixed it by adding a negative lookbehind for @ before the {

<img width="416" alt="after" src="https://cloud.githubusercontent.com/assets/2543659/10523530/270a61d8-737b-11e5-9cdc-eccb29bb3ae4.png">

Adding this to PR #42  because it's related to #30 and other issues.
