### ISSUE TITLE
css property value not recognized when it contains dash

### ISSUE THREAD

**Issue by yomed** [atom/language-less#38]
```
transition: left .2s ease-out;
```

<img width="324" alt="screen shot 2015-09-20 at 2 03 14 pm" src="https://cloud.githubusercontent.com/assets/3595986/9982904/6f05106c-5fa0-11e5-8c2b-c98cb7343949.png">

It looks like the dash is recognized as an operator, so the full property value doesn't get highlighted correctly.

**Comment by braver** [comment]
I just tried to make it catch `-webkit-flex` and it didn't either. I thing the `\b` (word boundary) is breaking this.

**Comment by braver** [comment]
If I'm correct replacing the `\\b` at the start of line 363 with  `(?<![-a-z])` accomplishes the same and allows it to capture `-webkit-flex`.

@yomed you're problem is different. The order of the 'ease' properties was wrong, it captured `ease` before checking `ease-in`.
