### ISSUE TITLE
Hyphenated display property values not parsed as a whole term

### ISSUE THREAD

**Issue by miqid** [atom/language-less#44]
Hello there.

A minor niggle to report. I noticed the `language-less` package treating the hyphen between some `display` property values as an operator. Screenshot to show this happening below.

![preview](https://cloud.githubusercontent.com/assets/2031402/11714185/54b8385c-9f73-11e5-97b9-04337b32c5c8.png)

After noticing this, I scoured around briefly for other CSS property values using hyphens. However, all of which I tried seemed to treat the hyphens properly.

**Comment by silvestreh** [comment]
Same happens with properties, not just values.

![captura de pantalla 2015-12-10 a las 12 36 27](https://cloud.githubusercontent.com/assets/1133339/11719723/d0375fc8-9f3a-11e5-832e-0dbe9c756732.png)

Some properties do show as expected, like `max-width` in the screenshot.

**Comment by braver** [comment]
@50Wliu language-less in Atom 1.3.2 is still at 0.28.3. It needs to be bumped to 0.29.0 to pull in my big overhaul. That will get those fixes in hands of users.

**Comment by 50Wliu** [comment]
@braver All right, that's good to know.  I'm closing this then since it's already been fixed.
