### ISSUE TITLE
Parentheses without quotes bug

### ISSUE THREAD

**Issue by VPenkov** [atom/language-less#45]
Syntax like ``background-image: url(../img/img.jpg);`` is problematic because if the path is not enclosed with quotes, the text afterwards is being treated as a part of the path.

![image](https://cloud.githubusercontent.com/assets/1693651/12854429/5e4eb8e0-cc42-11e5-9517-e492e78d002e.png)

**Comment by 50Wliu** [comment]
@VPenkov If you shorten the line so the string ends at `base64`, does the syntax highlighting correct itself?

**Comment by VPenkov** [comment]
Yes, it's fine then.
But still one more issue persists with this:
![image](https://cloud.githubusercontent.com/assets/1693651/12861637/8c2c0b3e-cc6d-11e5-8338-41f672945c10.png)

Possibly unrelated but seems related.

**Comment by 50Wliu** [comment]
Ok, the issue you're describing is a limitation in Atom where it'll stop parsing past 100 tokens: please see atom/atom#1667 for more details.

Can you please open a new issue for the background bug?  Thanks!
