### ISSUE TITLE
Indent is lost when adding new lines

### ISSUE THREAD

**Issue by gabrihellmateus** [atom/language-less#48]
A same [issue](https://github.com/atom/language-less/issues/1#issue) was closed, but the error still happens.

![Example](http://g.recordit.co/y9sTFakFRI.gif)

I'm using Atom 1.5.3 version and this issue is only in .less files (I've tested in .scss files as well).

**Comment by OctavioBR** [comment]
+1

**Comment by gabrihellmateus** [comment]
Nevermind, turns out the `language-source` it was disabled in `config.cson`.

Now works!
