### ISSUE TITLE
Config file?

### ISSUE THREAD

**Issue by brettz9** [atom/language-less#52]
In looking at some Less code (in the file-type-icons package), certain errors are occurring, apparently because they are referencing built-in files or variables which are not available at a location relative to the current file.

Some examples include:

```less
@import "ui-variables";
```

and

```less
line-height: @component-line-height;
```

Could you allow a config file which indicates which variables are predefined (or to indicate that this is for an Atom package)?

**Comment by 50Wliu** [comment]
language-less only provides syntax highlighting and does not lint your files.
