### ISSUE TITLE
Element with attribute selector not hightlight correctly 

### ISSUE THREAD

**Issue by wingyplus** [atom/language-less#70]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Notice: I found this on Syntax highlight wrong color when writing element with attribute.

### Steps to Reproduce

Writing selector below.

```less
atom-text-editor[mini] .scroll-view {
  padding-left: 1px;
}
```

**Expected behavior:**

It should highlight same as element selector

<img width="274" alt="screen shot 2560-01-27 at 11 14 09 am" src="https://cloud.githubusercontent.com/assets/484530/22360409/0d951bfc-e482-11e6-81dd-97a4b879b0f6.png">

**Actual behavior:**

It highlight

<img width="322" alt="screen shot 2560-01-27 at 11 10 58 am" src="https://cloud.githubusercontent.com/assets/484530/22360336/549b70e2-e481-11e6-86f1-505ac5f08c87.png">

### Versions

atom@1.13.0
language-less@0.29.6

**Comment by 50Wliu** [comment]
This has been fixed, most likely by atom/language-css#99.  Should be out in Atom 1.15.0.
