### ISSUE TITLE
Request for contribution: Improve mixin parameter scopes

### ISSUE THREAD

**Issue by dsifford** [atom/language-less#81]
Hello again,

I'd like to work on improving the scope of less mixin parameters. ([See here](https://github.com/dracula/visual-studio-code/blob/master/known_issues.md#less))

Currently, given the following mixin...

```less
.mymixin(@x: 5px) {}
```

the following scopes are given...

```less
  .mymixin(@x: 5px) {}
//^^^^^^^^source.css.less entity.other.attribute-name.class.mixin.css
//        ^source.css.less meta.brace.round.css
//         ^source.css.less variable.other.lesspunctuation.definition.variable.less
//          ^source.css.lessvariable.other.less
//           ^source.css.less punctuation.separator.key-value.css
//             ^source.css.less constant.numeric.css
//              ^^source.css.less constant.numeric.css keyword.other.unit.px.css
//                ^source.css.less meta.brace.round.css
```

What I'm proposing to change is to make it instead produce this...

```less
  .mymixin(@x: 5px) {}
//^^^^^^^^source.css.less meta.mixin.less meta.definition.mixin.less entity.name.mixin.less
//        ^source.css.less meta.mixin.less meta.parameters.less punctuation.definition.parameters.begin.less
//         ^^source.css.less meta.mixin.less meta.parameters.less variable.parameter.less
//           ^source.css.less meta.mixin.less meta.parameters.less keyword.operator.assignment.less
//             ^source.css.less constant.numeric.css
//              ^^source.css.less constant.numeric.css keyword.other.unit.px.css
//                ^source.css.less meta.mixin.less meta.parameters.less punctuation.definition.parameters.end.less
```

The scopes were chosen using Microsoft/TypeScript-TmLanguage as a reference because I personally think their grammar is one of the most meticulously designed and well-thought grammars that exists.

I started working on this already and it's pretty much done, but I wanted to make sure that this would be something accepted before adding a whole bunch of tests.

Let me know! Thanks 😄

**Comment by 50Wliu** [comment]
I totally agree with both changes.  All the other grammars do it like that.

**Comment by 50Wliu** [comment]
Commented too early :laughing:.

The only change I'm iffy on is the change from key-value to operator.assignment.  I think both scopes describe the intention pretty well.

**Comment by dsifford** [comment]
> However, the one change I would make to be consistent with other Atom grammars is adding .bracket.round to the punctuation classes (punctuation.definition.parameters.end.bracket.round.less)

> The only change I'm iffy on is the change from key-value to operator.assignment. I think both scopes describe the intention pretty well.

Sounds, reasonable to me!

>  Also, is there a reason the numeric scopes are missing meta.mixin.less?

Yep, must be a buggy scope 😝 ... I'll get that fixed.


I'll open the PR now with what I have so far and we can continue the conversation there.
