### ISSUE TITLE
Beautyfier makes nonsense

### ISSUE THREAD

**Issue by kolbma** [atom/language-less#85]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The following less-snippet becomes invalid less code after Atom Beautify.

```
@stylenr: 6;
@sl-color-var: @sl-color6;
@sl-color-shadow-var: @sl-color6;

.n4v-apos-spotlight-widgets.wrapper.spotlight {
  &.style@{stylenr} {
    background-color: @sl-color-var;
  }

  &.style@{stylenr}:before,
  &.style@{stylenr}:after {
    background-image: url("data:image/svg+xml;charset=utf8,%3Csvg xmlns='http://www.w3.org/2000/svg' width='100' height='100' viewBox='0 0 100 100' preserveAspectRatio='none'%3E%3Cpolygon points='0,100 100,0 100,100' style='fill:%232d3a69%3B;fill-opacity:0.5' /%3E%3C/svg%3E");
    box-shadow: inset 0 -1px 0 0 @sl-color-shadow-var, 0 1px 0 0 @sl-color-shadow-var;
  }
}
```

**Expected behavior:** 

Well maybe no change at all. But at least not the bullshit of the actual behavior.

**Actual behavior:** 
```
@stylenr: 6;
@sl-color-var: @sl-color6;
@sl-color-shadow-var: @sl-color6;

.n4v-apos-spotlight-widgets.wrapper.spotlight {
  &.style@{stylenr} {
    background-color: @sl-color-var;
  }

  &.style@,
  &.style@{stylenr}:before {
    stylenr
  }

  :after {
    background-image: url("data:image/svg+xml;charset=utf8,%3Csvg xmlns='http://www.w3.org/2000/svg' width='100' height='100' viewBox='0 0 100 100' preserveAspectRatio='none'%3E%3Cpolygon points='0,100 100,0 100,100' style='fill:%232d3a69%3B' /%3E%3C/svg%3E");
    box-shadow: inset 0 -1px 0 0 @sl-color-shadow-var, 0 1px 0 0 @sl-color-shadow-var;
  }
}
```

**Reproduces how often:** always

### Versions

Atom    : 1.22.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm  1.18.8
npm  3.10.10
node 6.9.5 ia32
python 2.7.13
git 2.14.1.windows.1
visual studio 2015

### Additional Information

none

**Comment by 50Wliu** [comment]
Thanks for contributing!

It appears that this is being caused by the [atom-beautify](https://atom.io/packages/atom-beautify) package, not language-less itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).

**Comment by 50Wliu** [comment]
In addition, please do not check the box indicating that you have completed all prerequisites if you actually haven't (in this case, there would be no way to beautify code in safe mode as atom-beautify would not have been loaded).

**Comment by kolbma** [comment]
Maybe you should provide then checkboxes for each step.
